mensagem_inicial = [
    ' - Entre no NEO com usuário Realtec.',
    ' - Deixe somente o NEO aberto e na aba PRINCIPAL.', 
    ' - Deixe SOMENTE os bancos do NEO e da NFC-e no arquivo ".ini".',
    ' - Não abra o NEO NFC-e, apenas o extraia.',
    ' - Caso as notas estejam sendo emitidas em contigência reinicie o computador.',
    ' - Validação do número de venda das NFC-e\'s deve ser manual (Em construção).',
    ' - Configure seu IP em Parâmetros: ',
    '   → Parâmetros → Outros → Serviços Neo → Fixar IP Conexão',
]

opcoesNEO = {
    'Parâmetros Gerais': 1,
    'Parâmetros de Contabilização': 2,
    'Cadastro Operadora Cartão': 3,
    'Cadastro Transações': 4,
    'Cadastro Finalizadora - Dinheiro':  11,
    'Cadastro Finalizadora - A prazo':  12,
    'Cadastro Finalizadora - Cartão a Vista':  13,
    'Cadastro Finalizadora - Cartão Débito':  14,
    'Cadastro Finalizadora - Cartão Crédito 2x':  15,
    'Cadastro Classificação Cliente':  16,
    'Cadastro Cliente 5':  17,
    'Cadastro Produto Padrão': 18,
    'Cadastro Produto 1': 19,
    'Cadastro Produto 2': 20,
    'Cadastro Produto 3': 21,
    'Cadastro Unidade Tributável': 22,
    'Ajuste de Estoque Produto 1': 23,
    'Ajuste de Estoque Produto 2': 24,
    'Ajuste de Estoque Produto 3': 25,
    'Cadastro Forma de Pagamento - A vista': 26,
    'Cadastro Forma de Pagamento - A prazo': 27,
    'Cadastro Terminal NFC-e': 28,
    'Configura Terminal NFC-e': 29,
    'Entra na NFC-e': 30,
    'Venda NFC-e Avulsa': 31,
    'DAV 1 -  Crediário': 32,
    'DAV 2 - A Vista': 33,
    'DAV Rápido 1': 34,
    'DAV Rápido 2': 35,
    'Importar DAV para NFC-e': 36,
    'Importar DAV Rápido para NFC-e': 37,
    'Venda Avulsa NFC-e 1': 38,
    'Venda Avulsa NFC-e 2': 39,
    'Venda Avulsa NFC-e 3': 40,
    'Conferência dos XML\'s': 41,
    'Fechar Caixa': 42,
    'Verificar Notas Confirmadas': 43,
    'Cancelar NFC-e\'s': 44,
    'Verificar Notas Canceladas': 45,
    'Verificar Estoque Final': 46,
}